### PR TITLE
Add preact to nanocomponent adapters

### PR DESCRIPTION
**Pull request by tkh44**
Preact does not have `createClass`. You can emulate it of course, but I did not know if you wanted to do that. Just let me know what you think and I will update PR if needed.

#2

### CODE REVIEW

**Comment by yoshuawuyts** [comment]
This is really cool! - whatever is most native to `preact` is ideal I think; don't think using `createClass` is desirable then (not even sure that's the best idea for `react` now haha - is it?)

Also I wonder: would it be better to use prototype methods? I know it's quite common in the preact / react world but it might save some compilation if we use prototypes. [Some quick googling](https://github.com/addyosmani/es6-equivalents-in-es5#classes) makes it seem we can replace:
```js
class Clx extends preact.Component {}
```
with:
```js
function Clx () {}
Clx.prototype = Object.create(preact.Component)
Clx.prototype.constructor = preact.Component
```
What do you think?

**Comment by tkh44** [comment]
That was what I was going to suggest.  I did a quick test [here (See Demo component)](http://codepen.io/tkh44/pen/oBpVqd?editors=0010#0) and it works fine. I wasn't sure if preact was doing any special tricks.

**Comment by yoshuawuyts** [comment]
cool! :D

**Comment by tkh44** [comment]
Converted to es5.

**Comment by yoshuawuyts** [comment]
Rad! - oh also @toddself just pointed out we can now just reuse the react
and preact code; e.g. alias it - that's like really cool :D

**Comment by yoshuawuyts** [comment]
`v1.2.0` :sparkles:

**Comment by developit** [comment]
Heh - I didn't even need to say anything lol.
Regarding prototype methods, preact doesn't care what gets used - the only requirement is that there is a `render()` method on the prototype. "Inheriting" from Component is just to get `setState()`.

**Pull request merged**
